### ISSUE TITLE
WARNING: Required namespace not provided for test_frame.core

### ISSUE THREAD

**Issue by wqhhust** [Day8/re-frame-template#8] opened 2015-08-22 07:51 UTC
When I change the clojurescript file and save, in the browser it pop a window saying
WARNING: Required namespace not provided for test_frame.core

How to remove the warning?

**Comment by mike-thompson-day8** [comment] 2015-08-22 13:49
I'm not seeing this.  

I just this second used the command:
`lein new re-frame pivot +re-com`

Then I:
`cd pivot`

Then I: 
`lein figwheel dev`

Then i started changing `pivot.views` ... and all seemed to work. 

Can you provide more details?

**Comment by gadfly361** [comment] 2015-08-22 19:02
I was able to reproduce the warning with the following:

```
lein new re-frame test_frame
cd test_frame
lein figwheel
```

@wqhhust The warning happened because the name of the application is `test_frame`.  When naming clojure(script) applications, use dashes instead of underscores.The warning will go away if you name the app `test-frame`.  I.e., the following will not result in a warning.

```
lein new re-frame test-frame
cd test-frame
lein figwheel
```

Let me know if this works :)

**Comment by gadfly361** [comment] 2015-08-27 06:25
@wqhhust closing because I think the above addresses the experienced issue. Please feel free to re-open if that isn't the case.

**Closed by gadfly361** 2015-08-27 06:25 UTC
