### ISSUE TITLE
Add sente

### ISSUE THREAD

**Issue by Jjunior130** [Day8/re-frame-template#43] opened 2016-12-18 10:09 UTC
lein new re-frame <pn> **+sente** +re-com +re-frisk +routes

**Comment by gadfly361** [comment] 2016-12-18 21:51
Thanks for the request! Always curious what the community is interested in :)

However, this particular request is a duplicate of [15](https://github.com/Day8/re-frame-template/issues/15) and was considered out of scope for this template.

**Closed** 2016-12-18 21:52 UTC
