### ISSUE TITLE
Template resource 'leiningen/new/re_frame/.clj-kondo/config.edn' not found.

### ISSUE THREAD

**Issue by nfedyashev** [day8/re-frame-template#126] opened 2020-04-16 16:45 UTC
```
macbook.local ➜  Projects lein new re-frame clojure-reframe-setup +cider +kondo +test +handler
Generating re-frame project.
Template resource 'leiningen/new/re_frame/.clj-kondo/config.edn' not found.
```

without `+kondo` everything works fine.
Let me know if you need any additional context/debug info.

**Comment by superstructor** [comment] 2020-04-29 22:45
Duplicate of #122. Both fixed as of today's release (v1.0.29). Thanks.

**Closed by superstructor** 2020-04-29 22:45 UTC
