### ISSUE TITLE
Unable to run `lein dev`

### ISSUE THREAD

**Issue by Wagk** [day8/re-frame-template#127] opened 2020-05-04 18:22 UTC
Hi, I'm not sure if there's a super obvious solution to this:

I ran the following (on windows 10):
```
lein new re-frame project
cd project
lein deps
npm install
lein dev
```

and `lein dev` returns me a result of:
```
λ lein dev
lein-shadow - preparing npm package.json
lein-shadow - installing npm packages
lein-shadow - npm package installation failed with
Error encountered performing task 'do' with profile(s): 'dev'
lein-shadow - npm package installation failed with
```

I'm starting out with clojure, and am not familiar with the tooling. Is this a misconfiguration on my end?

**Comment by superstructor** [comment] 2020-05-04 23:42
Thanks for the report @Wagk New users is a primary use case for re-frame-template so we definitely want to fix this if there is an issue.

First, its not causing your build to fail but your report highlighted a bug in our documentation. As I recently migrated the template to [`lein-shadow`](https://gitlab.com/nikperic/lein-shadow) that manages package.json, npm etc now so running `npm install` manually is just a no-op since there is no `package.json` file until `lein-shadow` writes it to disk. I have updated the documentation which will be reflected in the next release.

Otherwise the commands look correct.

I have tested on Windows 10 and it works for me with these versions:
```
> gcm lein
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  lein.ps1                                                      C:\Scoop\shims\lein.ps1

> lein --version
Leiningen 2.9.3 on Java 11.0.7 OpenJDK 64-Bit Client VM

> gcm node
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     node.exe                                           12.16.3.0  C:\Program Files\nodejs\node.exe

> node --version
v12.16.3

> gcm npm
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     npm.cmd                                            0.0.0.0    C:\Program Files\nodejs\npm.cmd

> npm --version
6.14.4
```

Can you see any output after the last line `npm package installation failed with` ?

**Comment by Wagk** [comment] 2020-05-04 23:43
@superstructor no I can't

**Comment by superstructor** [comment] 2020-05-04 23:50
Those version all look fine. [`gcm`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7) is a PowerShell thing like `which` on *nix.

After you run the failed command it should leave a non-empty `package.json` in that directory ?

What are the contents of the `package.json` file ? 

What is the output of running `npm install` in that directory **after** `lein dev` has failed ? 

`lein dev` writes out `package.json` and executes `npm install` via `lein-shadow` so just trying to peal back the layers and make the failure/error message visible so we can identify the root issue.

**Comment by Wagk** [comment] 2020-05-04 23:55
The contents of the `package.json` is the following:

```
{"dependencies":{},"devDependencies":{"shadow-cljs":"2.8.109"}}
```

**Comment by superstructor** [comment] 2020-05-05 01:23
So it looks like `npm install` by itself is successful ?

The [code for `lein-shadow` here](https://gitlab.com/nikperic/lein-shadow/-/blob/master/src/leiningen/shadow.clj#L38) simply
- executes `npm install`
- checks for a successful exit code
- if not successful prints stdout and stderr of the npm output to the console.

So its odd that 
- `npm install` doesn't appear to fail when run independently ? 
- there is not stdout or stderr to explain the error ?

**Comment by Wagk** [comment] 2020-05-05 01:42
yes, it's quite odd.
I attempted to run the command in the repl using the following:
```
λ lein repl
nREPL server started on port 52370 on host 127.0.0.1 - nrepl://127.0.0.1:52370
REPL-y 0.4.4, nREPL 0.6.0
Clojure 1.10.1
Java HotSpot(TM) Client VM 1.8.0_251-b08
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use '[clojure.java.shell :only [sh]])
nil
user=> (sh "npm" "install")
Execution error (IOException) at java.lang.ProcessImpl/create (REPL:-2).
CreateProcess error=2, The system cannot find the file specified
```
I'm not sure how exceptions map from java to clojure, though this would make sense if my shell is only capturing the `stdout` channel.

Does this help?

**Comment by superstructor** [comment] 2020-05-05 05:55
That is interesting. I can confirm that is your issue. Some kind of environmental or PATH issue with the JDK.

I get this for example:
```
> lein repl
REPL-y 0.4.4, nREPL 0.6.0
Clojure 1.10.1
OpenJDK 64-Bit Server VM 11.0.7+10
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use '[clojure.java.shell :only [sh]])
nil
user=> (sh "npm.cmd" "--version")
{:exit 0, :out "6.14.4\n", :err ""}
```

There is something we can change to improve, which is to print a clearer error message for this failure case when npm is not found. That is a lein-shadow issue and I will follow it up.

Therefore there is no bug in re-frame-template as such, so closing.

Thanks for the information and feedback, it has helped us improve the error messages for future users 😄

**Closed by superstructor** 2020-05-05 05:55 UTC

**Comment by Wagk** [comment] 2020-05-06 03:18
Thanks for the prompt response.

I've managed to successfully `lein dev` on WSL, so it does look like an issue local to my (windows) machine.

Cheers
